# Use root/example as user/password credentials
version: '3.3'

services:
  db:
    image: mysql
    container_name: mysqlDB
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: dev123
      MYSQL_DATABASE: musicos_online
    volumes:
      - ../mysql_data:/var/lib/mysql
      - ../db.sql:/docker-entrypoint-initdb.d/1.sql
